version: '3.8'
services:
  app:
    build: .
    container_name: shopping-service
    ports:
      - "8081:8081"
    env_file:
      - ./config/.env

# docker-compose up --build
# docker-compose up
# docker-compose down